### ISSUE TITLE
No camera image on rviz for op3_bringup_visualization.launch

### ISSUE THREAD

**Issue by Nbot07** [ROBOTIS-GIT/ROBOTIS-OP3-Demo#23]
No camera image is showing from OP3 in rviz when op3_bringup_visualization.launch is executed. 

As a work around, it is possible to see the image by launching:
`rosrun usb_cam usb_cam_node`
then changing the image topic in rviz to /usb_cam/image_raw

**Comment by kaym9n** [comment]
Sometimes the rviz configuration file seems to be wrong.
After running `op3_bringup_visualization.launch`, how about adding a camera topic manually?
Click `Add` button -> select `By topic` tab -> choose a camera of `/usb_cam_node/image_raw`

Or If camera calibration file is missing, you can not see the camera topic in rviz.
check the file in the folder of `/home/username/.ros/camera_info/camera.yaml`
If it doesn't exist, you should calibrate the camera.
Refer this [link](http://wiki.ros.org/camera_calibration) please.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
